/* AUTO-GENERATED by tooling/prototype/export-lessons.ts — DO NOT EDIT BY HAND.
 * Regenerate: npm run prototype:export
 *
 * Real, CI-validated lesson content mapped into the prototype LESSONS shape.
 * Keyed l<ordinal>; merged over MOCK_LESSONS in apps/prototype/index.html.
 * SYNTHESIZED (prototype-only, no schema source): lesson.prof (demo bars, 92),
 *   vocab.hint (from example pair), passage-seg.hint + quiz.hint (generic nudges).
 * DROPPED (no prototype slot): sentence.difficulty.
 * METADATA (no UI consumer): lesson.objective, lesson.conversation.
 * Lessons exported: a1-01-hola-me-llamo -> l1, a1-02-soy-asi -> l2, a1-03-que-haces -> l3.
 */
window.AIDIOMA_LESSONS = {
  "l1": {
    "n": 1,
    "title": "Hola: greetings and introducing yourself",
    "prof": 92,
    "objective": "You can greet someone and write a simple introduction giving your name and where you're from.",
    "conversation": {
      "scenario": "Meeting someone new at a language exchange.",
      "openingLine": "Hola, me llamo Camila. Soy de México.",
      "openingLineGloss": "Hi, my name is Camila. I'm from Mexico.",
      "goalPhrases": [
        "Hola, me llamo…",
        "Soy de Colombia.",
        "Buenos días.",
        "Gracias."
      ]
    },
    "items": {
      "quiz": [
        {
          "type": "mc",
          "label": "Quiz",
          "prompt": "___ de México. (I'm from Mexico)",
          "options": [
            "Soy",
            "Eres",
            "Es",
            "Son"
          ],
          "correct": 0,
          "why": "Use soy, the yo form of ser, to say where you're from.",
          "hint": "Re-read the prompt and pick the form that fits."
        },
        {
          "type": "mc",
          "label": "Quiz",
          "prompt": "___ señora es de Colombia.",
          "options": [
            "La",
            "El",
            "Los",
            "Un"
          ],
          "correct": 0,
          "why": "Señora is feminine singular, so it takes la.",
          "hint": "Re-read the prompt and pick the form that fits."
        },
        {
          "type": "mc",
          "label": "Quiz",
          "prompt": "In the introduction card, where is Camila from?",
          "options": [
            "De México.",
            "De Colombia.",
            "De Perú.",
            "De Chile."
          ],
          "correct": 0,
          "why": "The card says «Soy de México.»",
          "hint": "Re-read the prompt and pick the form that fits."
        }
      ],
      "words": [
        {
          "type": "flash",
          "es": "hola",
          "en": "hello / hi",
          "pos": "expression",
          "accEs": [
            "hola"
          ],
          "accEn": [
            "hello",
            "hi"
          ],
          "hint": "Hola, señora. — Hi, ma'am."
        },
        {
          "type": "flash",
          "es": "adiós",
          "en": "goodbye",
          "pos": "expression",
          "accEs": [
            "adiós"
          ],
          "accEn": [
            "goodbye"
          ],
          "hint": "Adiós, señor. — Goodbye, sir."
        },
        {
          "type": "flash",
          "es": "gracias",
          "en": "thank you",
          "pos": "expression",
          "accEs": [
            "gracias"
          ],
          "accEn": [
            "thank you"
          ],
          "hint": "Gracias, señora. — Thank you, ma'am."
        },
        {
          "type": "flash",
          "es": "por favor",
          "en": "please",
          "pos": "phrase",
          "accEs": [
            "por favor"
          ],
          "accEn": [
            "please"
          ],
          "hint": "Por favor, señor. — Please, sir."
        },
        {
          "type": "flash",
          "es": "perdón",
          "en": "excuse me / sorry",
          "pos": "expression",
          "accEs": [
            "perdón"
          ],
          "accEn": [
            "excuse me",
            "sorry"
          ],
          "hint": "Perdón, señora. — Excuse me, ma'am."
        },
        {
          "type": "flash",
          "es": "buenos días",
          "en": "good morning",
          "pos": "phrase",
          "accEs": [
            "buenos días"
          ],
          "accEn": [
            "good morning"
          ],
          "hint": "Buenos días, señor. — Good morning, sir."
        },
        {
          "type": "flash",
          "es": "buenas noches",
          "en": "good evening / good night",
          "pos": "phrase",
          "accEs": [
            "buenas noches"
          ],
          "accEn": [
            "good evening",
            "good night"
          ],
          "hint": "Buenas noches, señora. — Good evening, ma'am."
        },
        {
          "type": "flash",
          "es": "señor",
          "en": "sir / man / Mr.",
          "pos": "noun · m",
          "accEs": [
            "señor"
          ],
          "accEn": [
            "sir",
            "man",
            "mr."
          ],
          "hint": "El señor es de México. — The man is from Mexico."
        },
        {
          "type": "flash",
          "es": "señora",
          "en": "ma'am / lady / Mrs.",
          "pos": "noun · f",
          "accEs": [
            "señora"
          ],
          "accEn": [
            "ma'am",
            "lady",
            "mrs."
          ],
          "hint": "La señora es de Colombia. — The lady is from Colombia."
        },
        {
          "type": "flash",
          "es": "me llamo",
          "en": "my name is (I'm called)",
          "pos": "phrase · chunk",
          "accEs": [
            "me llamo"
          ],
          "accEn": [
            "my name is"
          ],
          "hint": "Me llamo Ana. — My name is Ana."
        },
        {
          "type": "flash",
          "es": "te llamas",
          "en": "your name is (you're called)",
          "pos": "phrase · chunk",
          "accEs": [
            "te llamas"
          ],
          "accEn": [
            "your name is"
          ],
          "hint": "Tú te llamas Pedro. — Your name is Pedro."
        },
        {
          "type": "flash",
          "es": "se llama",
          "en": "his/her name is (he/she is called)",
          "pos": "phrase · chunk",
          "accEs": [
            "se llama"
          ],
          "accEn": [
            "his",
            "her name is"
          ],
          "hint": "Ella se llama Camila. — Her name is Camila."
        }
      ],
      "sentences": [
        {
          "type": "tr",
          "es": "Hola, soy Ana.",
          "en": "Hi, I'm Ana.",
          "accEs": [
            "hola, soy ana.",
            "hola, yo soy ana.",
            "¡hola! soy ana.",
            "¡hola! yo soy ana."
          ],
          "accEn": [
            "hi, i'm ana.",
            "hello, i'm ana.",
            "hi, i am ana."
          ],
          "hint": "Start with the greeting, then say who you are with the *yo* form of 'to be.'"
        },
        {
          "type": "tr",
          "es": "El señor es de Argentina.",
          "en": "The man is from Argentina.",
          "accEs": [
            "el señor es de argentina."
          ],
          "accEn": [
            "the man is from argentina.",
            "the gentleman is from argentina."
          ],
          "hint": "Use the word for 'the' with a masculine noun, then 'to be' for origin."
        },
        {
          "type": "tr",
          "es": "Me llamo Diego y soy de Colombia.",
          "en": "My name is Diego and I'm from Colombia.",
          "accEs": [
            "me llamo diego y soy de colombia.",
            "yo me llamo diego y soy de colombia.",
            "me llamo diego y yo soy de colombia.",
            "yo me llamo diego y yo soy de colombia.",
            "soy diego y soy de colombia."
          ],
          "accEn": [
            "my name is diego and i'm from colombia.",
            "my name is diego and i am from colombia."
          ],
          "hint": "Give your name with the set phrase, then add where you're from with *ser*."
        },
        {
          "type": "tr",
          "es": "La señora es de Colombia.",
          "en": "The lady is from Colombia.",
          "accEs": [
            "la señora es de colombia."
          ],
          "accEn": [
            "the lady is from colombia.",
            "the woman is from colombia."
          ],
          "hint": "Use 'the' for a feminine noun, then 'to be' for origin."
        },
        {
          "type": "tr",
          "es": "Buenos días. Me llamo Diego y soy de Perú.",
          "en": "Good morning. My name is Diego and I'm from Peru.",
          "accEs": [
            "buenos días. me llamo diego y soy de perú.",
            "buenos días. yo me llamo diego y soy de perú.",
            "buenos días. me llamo diego y yo soy de perú.",
            "buenos días. yo me llamo diego y yo soy de perú.",
            "buen día. me llamo diego y soy de perú."
          ],
          "accEn": [
            "good morning. my name is diego and i'm from peru.",
            "good morning. my name is diego and i am from peru."
          ],
          "hint": "Open with a morning greeting, give your name, then your origin."
        },
        {
          "type": "tr",
          "es": "Ella se llama Sofía y es de Perú.",
          "en": "Her name is Sofía and she's from Peru.",
          "accEs": [
            "ella se llama sofía y es de perú.",
            "se llama sofía y es de perú.",
            "es de perú y se llama sofía.",
            "ella es de perú y se llama sofía."
          ],
          "accEn": [
            "her name is sofía and she's from peru.",
            "her name is sofia and she is from peru."
          ],
          "hint": "Say her name with the third-person set phrase, then her origin."
        },
        {
          "type": "tr",
          "es": "Buenas noches. Soy de México.",
          "en": "Good evening. I'm from Mexico.",
          "accEs": [
            "buenas noches. soy de méxico.",
            "buenas noches. yo soy de méxico.",
            "buenas noches, soy de méxico.",
            "buenas noches, yo soy de méxico."
          ],
          "accEn": [
            "good evening. i'm from mexico.",
            "good evening. i am from mexico.",
            "good night. i'm from mexico."
          ],
          "hint": "Open with an evening greeting, then say where you're from."
        },
        {
          "type": "tr",
          "es": "Yo soy de México y tú eres de Chile.",
          "en": "I'm from Mexico and you're from Chile.",
          "accEs": [
            "yo soy de méxico y tú eres de chile.",
            "soy de méxico y eres de chile.",
            "soy de méxico y tú eres de chile.",
            "yo soy de méxico y eres de chile."
          ],
          "accEn": [
            "i'm from mexico and you're from chile.",
            "i am from mexico and you are from chile."
          ],
          "hint": "Two people: give your origin, then the other person's, keeping both subjects."
        },
        {
          "type": "tr",
          "es": "Gracias, señor.",
          "en": "Thank you, sir.",
          "accEs": [
            "gracias, señor.",
            "muchas gracias, señor.",
            "señor, gracias.",
            "¡gracias, señor!"
          ],
          "accEn": [
            "thank you, sir.",
            "thanks, sir."
          ],
          "hint": "Thank someone, then address a man politely."
        },
        {
          "type": "tr",
          "es": "Perdón, señora.",
          "en": "Excuse me, ma'am.",
          "accEs": [
            "perdón, señora.",
            "señora, perdón.",
            "¡perdón, señora!"
          ],
          "accEn": [
            "excuse me, ma'am.",
            "sorry, ma'am.",
            "pardon me, ma'am."
          ],
          "hint": "Apologize or excuse yourself, then address a woman politely."
        },
        {
          "type": "tr",
          "es": "Por favor, señor.",
          "en": "Please, sir.",
          "accEs": [
            "por favor, señor.",
            "señor, por favor.",
            "¡por favor, señor!"
          ],
          "accEn": [
            "please, sir."
          ],
          "hint": "Say 'please,' then address a man politely."
        },
        {
          "type": "tr",
          "es": "Adiós, señora.",
          "en": "Goodbye, ma'am.",
          "accEs": [
            "adiós, señora.",
            "señora, adiós.",
            "¡adiós, señora!"
          ],
          "accEn": [
            "goodbye, ma'am.",
            "bye, ma'am."
          ],
          "hint": "Say goodbye, then address a woman politely."
        },
        {
          "type": "tr",
          "es": "Yo me llamo Ana y tú te llamas Pedro.",
          "en": "My name is Ana and your name is Pedro.",
          "accEs": [
            "yo me llamo ana y tú te llamas pedro.",
            "me llamo ana y te llamas pedro.",
            "me llamo ana y tú te llamas pedro.",
            "yo me llamo ana y te llamas pedro."
          ],
          "accEn": [
            "my name is ana and your name is pedro.",
            "my name is ana and your name's pedro."
          ],
          "hint": "Give your name, then the other person's, using the two set phrases."
        },
        {
          "type": "tr",
          "es": "Nosotros somos de Colombia y ellos son de México.",
          "en": "We're from Colombia and they're from Mexico.",
          "accEs": [
            "nosotros somos de colombia y ellos son de méxico.",
            "somos de colombia y son de méxico.",
            "somos de colombia y ellos son de méxico.",
            "nosotros somos de colombia y son de méxico.",
            "nosotras somos de colombia y ellas son de méxico."
          ],
          "accEn": [
            "we're from colombia and they're from mexico.",
            "we are from colombia and they are from mexico."
          ],
          "hint": "Two groups: 'we' and 'they,' each with their origin."
        }
      ],
      "story": [
        {
          "type": "seg",
          "context": "",
          "es": "Hola. Me llamo Camila.",
          "accept": [
            "hi. my name is camila.",
            "hello. my name is camila."
          ],
          "show": "Hi. My name is Camila.",
          "hint": "Translate the highlighted Spanish line into natural English."
        },
        {
          "type": "seg",
          "context": "Hola. Me llamo Camila.",
          "es": "Soy de México.",
          "accept": [
            "i'm from mexico.",
            "i am from mexico."
          ],
          "show": "I'm from Mexico.",
          "hint": "Translate the highlighted Spanish line into natural English."
        },
        {
          "type": "seg",
          "context": "Hola. Me llamo Camila. Soy de México.",
          "es": "Él se llama Diego y es de Colombia.",
          "accept": [
            "his name is diego and he's from colombia.",
            "he's called diego and he is from colombia."
          ],
          "show": "His name is Diego and he's from Colombia.",
          "hint": "Translate the highlighted Spanish line into natural English."
        },
        {
          "type": "seg",
          "context": "Hola. Me llamo Camila. Soy de México. Él se llama Diego y es de Colombia.",
          "es": "Gracias. Adiós.",
          "accept": [
            "thank you. goodbye.",
            "thanks. bye."
          ],
          "show": "Thank you. Goodbye.",
          "hint": "Translate the highlighted Spanish line into natural English."
        }
      ]
    }
  },
  "l2": {
    "n": 2,
    "title": "Soy así: describing people",
    "prof": 92,
    "objective": "You can write short sentences describing what a person is like, with correct gender/number agreement.",
    "conversation": {
      "scenario": "Chatting with a friend about people you both know.",
      "openingLine": "Hola. Ella se llama Camila y es muy simpática.",
      "openingLineGloss": "Hi. Her name is Camila and she's very friendly.",
      "goalPhrases": [
        "Ella es alta y simpática.",
        "Él es mexicano.",
        "Yo soy amable.",
        "Ella se llama Ana."
      ]
    },
    "items": {
      "quiz": [
        {
          "type": "mc",
          "label": "Quiz",
          "prompt": "La señora es ___.",
          "options": [
            "simpática",
            "simpático",
            "simpáticos",
            "simpáticas"
          ],
          "correct": 0,
          "why": "Señora is feminine singular, so the adjective takes the feminine singular form simpática.",
          "hint": "Re-read the prompt and pick the form that fits."
        },
        {
          "type": "mc",
          "label": "Quiz",
          "prompt": "Ellos son ___.",
          "options": [
            "altos",
            "alto",
            "alta",
            "altas"
          ],
          "correct": 0,
          "why": "Ellos is masculine plural, so 'tall' agrees as altos.",
          "hint": "Re-read the prompt and pick the form that fits."
        },
        {
          "type": "mc",
          "label": "Quiz",
          "prompt": "Nosotras somos ___.",
          "options": [
            "colombianas",
            "colombianos",
            "colombiana",
            "colombiano"
          ],
          "correct": 0,
          "why": "Nosotras is feminine plural, so the nationality is colombianas.",
          "hint": "Re-read the prompt and pick the form that fits."
        },
        {
          "type": "mc",
          "label": "Quiz",
          "prompt": "In the reading, where is Diego from?",
          "options": [
            "De Colombia.",
            "De México.",
            "De Perú.",
            "De Chile."
          ],
          "correct": 0,
          "why": "The reading says «Él se llama Diego y es de Colombia.»",
          "hint": "Re-read the prompt and pick the form that fits."
        }
      ],
      "words": [
        {
          "type": "flash",
          "es": "alto",
          "en": "tall",
          "pos": "adjective",
          "accEs": [
            "alto"
          ],
          "accEn": [
            "tall"
          ],
          "hint": "Él es alto. — He's tall."
        },
        {
          "type": "flash",
          "es": "joven",
          "en": "young",
          "pos": "adjective",
          "accEs": [
            "joven"
          ],
          "accEn": [
            "young"
          ],
          "hint": "Ella es joven. — She's young."
        },
        {
          "type": "flash",
          "es": "bonito",
          "en": "pretty / nice-looking",
          "pos": "adjective",
          "accEs": [
            "bonito"
          ],
          "accEn": [
            "pretty",
            "nice-looking"
          ],
          "hint": "Ella es bonita. — She's pretty."
        },
        {
          "type": "flash",
          "es": "simpático",
          "en": "nice / friendly",
          "pos": "adjective",
          "accEs": [
            "simpático"
          ],
          "accEn": [
            "nice",
            "friendly"
          ],
          "hint": "El señor es simpático. — The man is friendly."
        },
        {
          "type": "flash",
          "es": "inteligente",
          "en": "intelligent / smart",
          "pos": "adjective",
          "accEs": [
            "inteligente"
          ],
          "accEn": [
            "intelligent",
            "smart"
          ],
          "hint": "Tú eres inteligente. — You're smart."
        },
        {
          "type": "flash",
          "es": "delgado",
          "en": "slim / thin",
          "pos": "adjective",
          "accEs": [
            "delgado"
          ],
          "accEn": [
            "slim",
            "thin"
          ],
          "hint": "Él es delgado. — He's slim."
        },
        {
          "type": "flash",
          "es": "amable",
          "en": "kind",
          "pos": "adjective",
          "accEs": [
            "amable"
          ],
          "accEn": [
            "kind"
          ],
          "hint": "La señora es amable. — The lady is kind."
        },
        {
          "type": "flash",
          "es": "trabajador",
          "en": "hardworking",
          "pos": "adjective",
          "accEs": [
            "trabajador"
          ],
          "accEn": [
            "hardworking"
          ],
          "hint": "El señor es trabajador. — The man is hardworking."
        },
        {
          "type": "flash",
          "es": "mexicano",
          "en": "Mexican",
          "pos": "adjective",
          "accEs": [
            "mexicano"
          ],
          "accEn": [
            "mexican"
          ],
          "hint": "Él es mexicano. — He's Mexican."
        },
        {
          "type": "flash",
          "es": "colombiano",
          "en": "Colombian",
          "pos": "adjective",
          "accEs": [
            "colombiano"
          ],
          "accEn": [
            "colombian"
          ],
          "hint": "Ella es colombiana. — She's Colombian."
        }
      ],
      "sentences": [
        {
          "type": "tr",
          "es": "Yo soy alto.",
          "en": "I'm tall.",
          "accEs": [
            "yo soy alto.",
            "soy alto.",
            "soy alta.",
            "yo soy alta."
          ],
          "accEn": [
            "i'm tall.",
            "i am tall."
          ],
          "hint": "Say who you are with the *yo* form of 'to be,' then the adjective for 'tall.'"
        },
        {
          "type": "tr",
          "es": "Ella es colombiana y bonita.",
          "en": "She's Colombian and pretty.",
          "accEs": [
            "ella es colombiana y bonita.",
            "es colombiana y bonita.",
            "ella es bonita y colombiana.",
            "es bonita y colombiana.",
            "ella es colombiana y linda.",
            "es colombiana y linda."
          ],
          "accEn": [
            "she's colombian and pretty.",
            "she is colombian and pretty."
          ],
          "hint": "Both adjectives describe a woman, so both must take the feminine form."
        },
        {
          "type": "tr",
          "es": "El señor es trabajador y amable.",
          "en": "The man is hardworking and kind.",
          "accEs": [
            "el señor es trabajador y amable.",
            "es trabajador y amable.",
            "el señor es amable y trabajador.",
            "es amable y trabajador."
          ],
          "accEn": [
            "the man is hardworking and kind.",
            "the gentleman is hardworking and kind."
          ],
          "hint": "Use masculine 'the' with the man, then 'to be' plus two qualities joined by 'and.'"
        },
        {
          "type": "tr",
          "es": "Tú eres joven y amable.",
          "en": "You're young and kind.",
          "accEs": [
            "tú eres joven y amable.",
            "eres joven y amable.",
            "tú eres amable y joven.",
            "eres amable y joven."
          ],
          "accEn": [
            "you're young and kind.",
            "you are young and kind."
          ],
          "hint": "Address the other person with the *tú* form of 'to be,' then two qualities."
        },
        {
          "type": "tr",
          "es": "Nosotros somos mexicanos.",
          "en": "We're Mexican.",
          "accEs": [
            "nosotros somos mexicanos.",
            "somos mexicanos.",
            "nosotras somos mexicanas.",
            "somos mexicanas."
          ],
          "accEn": [
            "we're mexican.",
            "we are mexican."
          ],
          "hint": "A group including you: use the 'we' form and make the nationality plural."
        },
        {
          "type": "tr",
          "es": "Ellas son inteligentes y amables.",
          "en": "They're smart and kind.",
          "accEs": [
            "ellas son inteligentes y amables.",
            "son inteligentes y amables.",
            "ellas son amables e inteligentes.",
            "son amables e inteligentes.",
            "ellos son inteligentes y amables.",
            "ellos son amables e inteligentes."
          ],
          "accEn": [
            "they're smart and kind.",
            "they are intelligent and kind.",
            "they're intelligent and kind."
          ],
          "hint": "Several women: use the 'they' form and make both adjectives plural."
        },
        {
          "type": "tr",
          "es": "Él es delgado y joven.",
          "en": "He's slim and young.",
          "accEs": [
            "él es delgado y joven.",
            "es delgado y joven.",
            "él es joven y delgado.",
            "es joven y delgado."
          ],
          "accEn": [
            "he's slim and young.",
            "he is slim and young.",
            "he's thin and young."
          ],
          "hint": "Describe a man with 'to be' plus two qualities joined by 'and.'"
        },
        {
          "type": "tr",
          "es": "La señora es simpática y amable.",
          "en": "The lady is friendly and kind.",
          "accEs": [
            "la señora es simpática y amable.",
            "es simpática y amable.",
            "la señora es amable y simpática.",
            "es amable y simpática."
          ],
          "accEn": [
            "the lady is friendly and kind.",
            "the woman is nice and kind."
          ],
          "hint": "Use feminine 'the' with the lady, then two qualities; only one adjective changes shape."
        },
        {
          "type": "tr",
          "es": "Soy joven pero no soy alto.",
          "en": "I'm young, but I'm not tall.",
          "accEs": [
            "soy joven pero no soy alto.",
            "yo soy joven pero no soy alto.",
            "soy joven pero no soy alta.",
            "yo soy joven pero no soy alta."
          ],
          "accEn": [
            "i'm young, but i'm not tall.",
            "i am young but i'm not tall."
          ],
          "hint": "Two ideas joined by 'but': one thing you are, one thing you're not."
        },
        {
          "type": "tr",
          "es": "Ustedes son amables y trabajadores.",
          "en": "You're all kind and hardworking.",
          "accEs": [
            "ustedes son amables y trabajadores.",
            "son amables y trabajadores.",
            "ustedes son trabajadores y amables.",
            "son trabajadores y amables.",
            "ustedes son amables y trabajadoras.",
            "son amables y trabajadoras."
          ],
          "accEn": [
            "you're all kind and hardworking.",
            "you are kind and hardworking."
          ],
          "hint": "Address a group as 'you all,' then two qualities, both plural."
        },
        {
          "type": "tr",
          "es": "Ella es bonita y también es simpática.",
          "en": "She's pretty and also friendly.",
          "accEs": [
            "ella es bonita y también es simpática.",
            "es bonita y también es simpática.",
            "ella es simpática y también es bonita.",
            "es simpática y también es bonita.",
            "ella es bonita y simpática.",
            "ella es linda y también es simpática.",
            "ella es bonita y también simpática."
          ],
          "accEn": [
            "she's pretty and also friendly.",
            "she is pretty and also nice."
          ],
          "hint": "Add a second quality with 'also'; both adjectives describe a woman."
        },
        {
          "type": "tr",
          "es": "Nosotras somos colombianas y bonitas.",
          "en": "We're Colombian and pretty.",
          "accEs": [
            "nosotras somos colombianas y bonitas.",
            "somos colombianas y bonitas.",
            "nosotras somos bonitas y colombianas.",
            "somos bonitas y colombianas.",
            "nosotras somos colombianas y lindas.",
            "nosotros somos colombianos y bonitos."
          ],
          "accEn": [
            "we're colombian and pretty.",
            "we are colombian and pretty."
          ],
          "hint": "A group of women: use 'we' and make both adjectives feminine plural."
        },
        {
          "type": "tr",
          "es": "Ella es mexicana, es muy inteligente y también es simpática.",
          "en": "She's Mexican, very smart, and also friendly.",
          "accEs": [
            "ella es mexicana, es muy inteligente y también es simpática.",
            "es mexicana, es muy inteligente y también es simpática.",
            "ella es mexicana, muy inteligente y también simpática.",
            "es mexicana, muy inteligente y también simpática.",
            "ella es simpática, mexicana y muy inteligente."
          ],
          "accEn": [
            "she's mexican, very smart, and also friendly.",
            "she is mexican, very intelligent, and also nice."
          ],
          "hint": "Stack three qualities about the same woman; watch the feminine agreement on each."
        },
        {
          "type": "tr",
          "es": "Él se llama Diego y es joven y trabajador.",
          "en": "His name is Diego, and he's young and hardworking.",
          "accEs": [
            "él se llama diego y es joven y trabajador.",
            "se llama diego y es joven y trabajador.",
            "él se llama diego y es trabajador y joven.",
            "se llama diego y es trabajador y joven."
          ],
          "accEn": [
            "his name is diego, and he's young and hardworking.",
            "his name is diego and he is young and hardworking."
          ],
          "hint": "Give his name with the set phrase, then describe him with two qualities."
        }
      ],
      "story": [
        {
          "type": "seg",
          "context": "",
          "es": "Ella se llama Camila y es de México.",
          "accept": [
            "her name is camila and she's from mexico.",
            "she's called camila and she is from mexico."
          ],
          "show": "Her name is Camila and she's from Mexico.",
          "hint": "Translate the highlighted Spanish line into natural English."
        },
        {
          "type": "seg",
          "context": "Ella se llama Camila y es de México.",
          "es": "Ella es mexicana y muy simpática.",
          "accept": [
            "she's mexican and very friendly.",
            "she is mexican and very nice."
          ],
          "show": "She's Mexican and very friendly.",
          "hint": "Translate the highlighted Spanish line into natural English."
        },
        {
          "type": "seg",
          "context": "Ella se llama Camila y es de México. Ella es mexicana y muy simpática.",
          "es": "Él se llama Diego y es de Colombia.",
          "accept": [
            "his name is diego and he's from colombia.",
            "he's called diego and he is from colombia."
          ],
          "show": "His name is Diego and he's from Colombia.",
          "hint": "Translate the highlighted Spanish line into natural English."
        },
        {
          "type": "seg",
          "context": "Ella se llama Camila y es de México. Ella es mexicana y muy simpática. Él se llama Diego y es de Colombia.",
          "es": "Él es alto, delgado y trabajador.",
          "accept": [
            "he's tall, slim, and hardworking.",
            "he is tall, thin, and hardworking."
          ],
          "show": "He's tall, slim, and hardworking.",
          "hint": "Translate the highlighted Spanish line into natural English."
        },
        {
          "type": "seg",
          "context": "Ella se llama Camila y es de México. Ella es mexicana y muy simpática. Él se llama Diego y es de Colombia. Él es alto, delgado y trabajador.",
          "es": "Ellos son inteligentes y amables.",
          "accept": [
            "they're smart and kind.",
            "they are intelligent and kind."
          ],
          "show": "They're smart and kind.",
          "hint": "Translate the highlighted Spanish line into natural English."
        }
      ]
    }
  },
  "l3": {
    "n": 3,
    "title": "Qué haces: saying what you do",
    "prof": 92,
    "objective": "You can say what you and others do using regular -ar verbs, and ask a simple question about it.",
    "conversation": {
      "scenario": "A new coworker asks what you do day to day.",
      "openingLine": "Hola. Yo trabajo mucho. ¿Dónde trabajas tú?",
      "openingLineGloss": "Hi. I work a lot. Where do you work?",
      "goalPhrases": [
        "Yo trabajo y estudio.",
        "Hablo español.",
        "¿Dónde trabajas?",
        "No trabajo hoy."
      ]
    },
    "items": {
      "quiz": [
        {
          "type": "mc",
          "label": "Quiz",
          "prompt": "Yo ___ español.",
          "options": [
            "hablo",
            "hablas",
            "habla",
            "hablan"
          ],
          "correct": 0,
          "why": "For yo, an -ar verb ends in -o, so hablar becomes hablo.",
          "hint": "Re-read the prompt and pick the form that fits."
        },
        {
          "type": "mc",
          "label": "Quiz",
          "prompt": "Ella ___ mucho.",
          "options": [
            "estudia",
            "estudias",
            "estudio",
            "estudian"
          ],
          "correct": 0,
          "why": "For él/ella, an -ar verb ends in -a, so estudiar becomes estudia.",
          "hint": "Re-read the prompt and pick the form that fits."
        },
        {
          "type": "mc",
          "label": "Quiz",
          "prompt": "¿___ trabajas? (asking about a place)",
          "options": [
            "Dónde",
            "Qué",
            "No",
            "Y"
          ],
          "correct": 0,
          "why": "Dónde means 'where' and asks about a place; qué means 'what.'",
          "hint": "Re-read the prompt and pick the form that fits."
        },
        {
          "type": "mc",
          "label": "Quiz",
          "prompt": "Say it in Spanish: I don't work today",
          "options": [
            "No trabajo hoy.",
            "Trabajo no hoy.",
            "Trabajo hoy no.",
            "No hoy trabajo."
          ],
          "correct": 0,
          "why": "Negation puts no directly before the verb: No trabajo hoy.",
          "hint": "Re-read the prompt and pick the form that fits."
        }
      ],
      "words": [
        {
          "type": "flash",
          "es": "hablar",
          "en": "to speak / to talk",
          "pos": "verb",
          "accEs": [
            "hablar"
          ],
          "accEn": [
            "to speak",
            "to talk"
          ],
          "hint": "Yo hablo español. — I speak Spanish."
        },
        {
          "type": "flash",
          "es": "estudiar",
          "en": "to study",
          "pos": "verb",
          "accEs": [
            "estudiar"
          ],
          "accEn": [
            "to study"
          ],
          "hint": "Ella estudia mucho. — She studies a lot."
        },
        {
          "type": "flash",
          "es": "trabajar",
          "en": "to work",
          "pos": "verb",
          "accEs": [
            "trabajar"
          ],
          "accEn": [
            "to work"
          ],
          "hint": "Yo trabajo hoy. — I'm working today."
        },
        {
          "type": "flash",
          "es": "escuchar",
          "en": "to listen (to)",
          "pos": "verb",
          "accEs": [
            "escuchar"
          ],
          "accEn": [
            "to listen"
          ],
          "hint": "Escucho a la señora. — I listen to the lady."
        },
        {
          "type": "flash",
          "es": "descansar",
          "en": "to rest",
          "pos": "verb",
          "accEs": [
            "descansar"
          ],
          "accEn": [
            "to rest"
          ],
          "hint": "Hoy descanso. — Today I rest."
        },
        {
          "type": "flash",
          "es": "caminar",
          "en": "to walk",
          "pos": "verb",
          "accEs": [
            "caminar"
          ],
          "accEn": [
            "to walk"
          ],
          "hint": "Camino mucho. — I walk a lot."
        },
        {
          "type": "flash",
          "es": "practicar",
          "en": "to practice",
          "pos": "verb",
          "accEs": [
            "practicar"
          ],
          "accEn": [
            "to practice"
          ],
          "hint": "Practico español. — I practice Spanish."
        },
        {
          "type": "flash",
          "es": "necesitar",
          "en": "to need",
          "pos": "verb",
          "accEs": [
            "necesitar"
          ],
          "accEn": [
            "to need"
          ],
          "hint": "Necesito descansar. — I need to rest."
        }
      ],
      "sentences": [
        {
          "type": "tr",
          "es": "Hablo español y también inglés.",
          "en": "I speak Spanish and English too.",
          "accEs": [
            "hablo español y también inglés.",
            "yo hablo español y también inglés.",
            "hablo inglés y también español.",
            "yo hablo inglés y también español.",
            "hablo español e inglés también."
          ],
          "accEn": [
            "i speak spanish and english too.",
            "i speak both spanish and english.",
            "i speak spanish, and english too."
          ],
          "hint": "Say what you speak with the *yo* form of the -ar verb for 'to speak,' then add the second language with 'also.'"
        },
        {
          "type": "tr",
          "es": "Ella estudia mucho hoy.",
          "en": "She's studying a lot today.",
          "accEs": [
            "ella estudia mucho hoy.",
            "estudia mucho hoy.",
            "hoy ella estudia mucho.",
            "hoy estudia mucho.",
            "ella está estudiando mucho hoy.",
            "está estudiando mucho hoy."
          ],
          "accEn": [
            "she's studying a lot today.",
            "she studies a lot today."
          ],
          "hint": "Talk about 'she' with the third-person form of the -ar verb for 'to study.'"
        },
        {
          "type": "tr",
          "es": "¿Dónde trabajas?",
          "en": "Where do you work?",
          "accEs": [
            "¿dónde trabajas?",
            "¿en dónde trabajas?",
            "¿dónde trabajas tú?",
            "¿tú dónde trabajas?"
          ],
          "accEn": [
            "where do you work?",
            "where are you working?"
          ],
          "hint": "Ask about a place with the 'where' question word, then the *tú* form of 'to work.'"
        },
        {
          "type": "tr",
          "es": "Camino mucho hoy.",
          "en": "I'm walking a lot today.",
          "accEs": [
            "camino mucho hoy.",
            "yo camino mucho hoy.",
            "hoy camino mucho.",
            "hoy yo camino mucho.",
            "estoy caminando mucho hoy.",
            "yo estoy caminando mucho hoy."
          ],
          "accEn": [
            "i'm walking a lot today.",
            "i walk a lot today."
          ],
          "hint": "Say how much you walk with the *yo* form of the -ar verb for 'to walk.'"
        },
        {
          "type": "tr",
          "es": "Hoy practico español con la señora.",
          "en": "Today I'm practicing Spanish with the lady.",
          "accEs": [
            "hoy practico español con la señora.",
            "practico español con la señora hoy.",
            "yo practico español con la señora hoy.",
            "hoy yo practico español con la señora.",
            "hoy estoy practicando español con la señora.",
            "hoy yo estoy practicando español con la señora."
          ],
          "accEn": [
            "today i'm practicing spanish with the lady.",
            "today i practice spanish with the lady.",
            "i practice spanish with the woman today."
          ],
          "hint": "Say what you practice with the *yo* form, then add who you do it with using 'with.'"
        },
        {
          "type": "tr",
          "es": "Hoy escucho a la señora.",
          "en": "Today I'm listening to the lady.",
          "accEs": [
            "hoy escucho a la señora.",
            "escucho a la señora hoy.",
            "yo escucho a la señora hoy.",
            "hoy yo escucho a la señora.",
            "hoy estoy escuchando a la señora.",
            "hoy yo estoy escuchando a la señora."
          ],
          "accEn": [
            "today i'm listening to the lady.",
            "i listen to the lady today.",
            "today i listen to the woman."
          ],
          "hint": "Say who you're listening to with the *yo* form of 'to listen,' plus the little word *a* before the person."
        },
        {
          "type": "tr",
          "es": "Hoy no descanso.",
          "en": "Today I'm not resting.",
          "accEs": [
            "hoy no descanso.",
            "no descanso hoy.",
            "hoy yo no descanso.",
            "yo no descanso hoy.",
            "hoy no estoy descansando.",
            "hoy yo no estoy descansando."
          ],
          "accEn": [
            "today i'm not resting.",
            "i'm not resting today.",
            "today i don't rest."
          ],
          "hint": "Make it negative: put the little 'not' word right before the *yo* form of 'to rest.'"
        },
        {
          "type": "tr",
          "es": "Hoy necesito descansar.",
          "en": "Today I need to rest.",
          "accEs": [
            "hoy necesito descansar.",
            "necesito descansar hoy.",
            "yo necesito descansar hoy.",
            "hoy yo necesito descansar."
          ],
          "accEn": [
            "today i need to rest.",
            "i need to rest today."
          ],
          "hint": "Say what you need with the *yo* form of 'to need,' then leave the second verb in its dictionary form."
        },
        {
          "type": "tr",
          "es": "No hablo inglés pero estudio mucho.",
          "en": "I don't speak English, but I study a lot.",
          "accEs": [
            "no hablo inglés pero estudio mucho.",
            "yo no hablo inglés pero estudio mucho.",
            "no hablo inglés pero yo estudio mucho.",
            "yo no hablo inglés pero yo estudio mucho."
          ],
          "accEn": [
            "i don't speak english, but i study a lot.",
            "i don't speak english but i study a lot.",
            "i do not speak english, but i study a lot."
          ],
          "hint": "Two ideas joined by 'but': one thing you don't do, one thing you do."
        },
        {
          "type": "tr",
          "es": "¿Tú estudias español?",
          "en": "Do you study Spanish?",
          "accEs": [
            "¿tú estudias español?",
            "¿estudias español?",
            "¿estudias tú español?",
            "¿estudias español tú?"
          ],
          "accEn": [
            "do you study spanish?",
            "are you studying spanish?"
          ],
          "hint": "Turn a statement into a yes/no question — no extra word for 'do' is needed."
        },
        {
          "type": "tr",
          "es": "No trabajo hoy, descanso.",
          "en": "I'm not working today, I'm resting.",
          "accEs": [
            "no trabajo hoy, descanso.",
            "hoy no trabajo, descanso.",
            "no trabajo hoy, yo descanso.",
            "yo no trabajo hoy, descanso.",
            "no estoy trabajando hoy, estoy descansando.",
            "hoy no estoy trabajando, estoy descansando."
          ],
          "accEn": [
            "i'm not working today, i'm resting.",
            "i don't work today, i rest.",
            "i'm not working today; i'm resting."
          ],
          "hint": "Say what you're not doing, then what you are doing instead — two short *yo* actions."
        },
        {
          "type": "tr",
          "es": "Camino y practico español hoy.",
          "en": "I'm walking and practicing Spanish today.",
          "accEs": [
            "camino y practico español hoy.",
            "practico español y camino hoy.",
            "hoy camino y practico español.",
            "yo camino y practico español hoy.",
            "estoy caminando y practicando español hoy.",
            "hoy estoy caminando y practicando español."
          ],
          "accEn": [
            "i'm walking and practicing spanish today.",
            "i walk and practice spanish today."
          ],
          "hint": "Join two *yo* actions with 'and': one is walking, the other is practicing."
        },
        {
          "type": "tr",
          "es": "Hoy estudio y practico español, pero necesito descansar.",
          "en": "Today I study and practice Spanish, but I need to rest.",
          "accEs": [
            "hoy estudio y practico español, pero necesito descansar.",
            "hoy yo estudio y practico español, pero necesito descansar.",
            "estudio y practico español hoy, pero necesito descansar.",
            "hoy practico y estudio español, pero necesito descansar."
          ],
          "accEn": [
            "today i study and practice spanish, but i need to rest.",
            "today i study and practice spanish, but i need a rest."
          ],
          "hint": "Stack two things you do today, then contrast with something you need, joined by 'but.'"
        },
        {
          "type": "tr",
          "es": "¿Tú también trabajas y estudias?",
          "en": "Do you work and study too?",
          "accEs": [
            "¿tú también trabajas y estudias?",
            "¿también trabajas y estudias?",
            "¿trabajas y estudias también?",
            "¿también estudias y trabajas?"
          ],
          "accEn": [
            "do you work and study too?",
            "do you also work and study?"
          ],
          "hint": "Ask a yes/no question about two actions the other person also does, using 'also.'"
        }
      ],
      "story": [
        {
          "type": "seg",
          "context": "",
          "es": "Me llamo Ana y soy de México.",
          "accept": [
            "my name is ana and i'm from mexico.",
            "i'm called ana and i am from mexico."
          ],
          "show": "My name is Ana and I'm from Mexico.",
          "hint": "Translate the highlighted Spanish line into natural English."
        },
        {
          "type": "seg",
          "context": "Me llamo Ana y soy de México.",
          "es": "Hoy trabajo y estudio mucho.",
          "accept": [
            "today i work and study a lot.",
            "today i'm working and studying a lot."
          ],
          "show": "Today I work and study a lot.",
          "hint": "Translate the highlighted Spanish line into natural English."
        },
        {
          "type": "seg",
          "context": "Me llamo Ana y soy de México. Hoy trabajo y estudio mucho.",
          "es": "Hablo español con la señora.",
          "accept": [
            "i speak spanish with the lady.",
            "i talk in spanish with the woman."
          ],
          "show": "I speak Spanish with the lady.",
          "hint": "Translate the highlighted Spanish line into natural English."
        },
        {
          "type": "seg",
          "context": "Me llamo Ana y soy de México. Hoy trabajo y estudio mucho. Hablo español con la señora.",
          "es": "Camino mucho y practico inglés.",
          "accept": [
            "i walk a lot and practice english.",
            "i walk a lot and i practice english."
          ],
          "show": "I walk a lot and practice English.",
          "hint": "Translate the highlighted Spanish line into natural English."
        },
        {
          "type": "seg",
          "context": "Me llamo Ana y soy de México. Hoy trabajo y estudio mucho. Hablo español con la señora. Camino mucho y practico inglés.",
          "es": "No descanso mucho hoy.",
          "accept": [
            "i'm not resting much today.",
            "i don't rest much today."
          ],
          "show": "I'm not resting much today.",
          "hint": "Translate the highlighted Spanish line into natural English."
        },
        {
          "type": "seg",
          "context": "Me llamo Ana y soy de México. Hoy trabajo y estudio mucho. Hablo español con la señora. Camino mucho y practico inglés. No descanso mucho hoy.",
          "es": "¡Necesito descansar!",
          "accept": [
            "i need to rest!",
            "i need a rest!"
          ],
          "show": "I need to rest!",
          "hint": "Translate the highlighted Spanish line into natural English."
        }
      ]
    }
  }
};
